import type { Metadata } from "next";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { partners, buildEskyFlightsUrl } from "@/lib/partners";

export const metadata:Metadata={title:"Jarmarki bożonarodzeniowe 2026 — terminy i wyjazdy | Tripownia.pl",description:"Wiedeń, Praga, Berlin i Budapeszt: kalendarz jarmarków 2026, propozycje terminów, loty, noclegi i atrakcje.",alternates:{canonical:"/jarmarki-bozonarodzeniowe"}};
const ideas=[
 {city:"Wiedeń",flag:"🇦🇹",dates:"20–23 listopada 2026",market:"Rathausplatz: 13.11–26.12 · Schönbrunn: 6.11–6.01",image:"/images/destinations/wieden.jpg",airport:"VIE",see:"Rathausplatz · Schönbrunn · Belweder · Stephansplatz"},
 {city:"Praga",flag:"🇨🇿",dates:"4–7 grudnia 2026",market:"Rynek Staromiejski i Václavské náměstí: 28.11–6.01",image:"/images/destinations/praga.jpg",airport:"PRG",see:"Rynek Staromiejski · Most Karola · Zamek · Mala Strana"},
 {city:"Berlin",flag:"🇩🇪",dates:"27–30 listopada 2026",market:"Charlottenburg: 23.11–27.12 · część jarmarków od początku listopada",image:"/images/destinations/berlin.jpg",airport:"BER",see:"Charlottenburg · Gendarmenmarkt okolice · East Side Gallery · Mitte"},
 {city:"Budapeszt",flag:"🇭🇺",dates:"11–14 grudnia 2026",market:"Sezon adwentowy — najlepiej sprawdzać oficjalny kalendarz przed rezerwacją",image:"/images/destinations/budapeszt.jpg",airport:"BUD",see:"Bazylika św. Stefana · Vörösmarty tér · Parlament · termy"},
];
function esky(city:string,airport:string,dates:string){const [d1,d2]=dates.replace(' 2026','').split('–').map(x=>x.trim()); const months:{[k:string]:string}={listopada:'11',grudnia:'12'}; const parse=(x:string, fallbackMonth:string)=>{const p=x.split(' '); return `2026-${months[p[1]]||fallbackMonth}-${p[0].padStart(2,'0')}`}; const p1=d1.split(' '); const p2=d2.split(' '); const m1=months[p1[1]]||months[p2[1]]||'12'; const dep=parse(d1,m1),ret=parse(d2,m1); return buildEskyFlightsUrl(`https://www2.esky.pl/flights/search/mp/WAWA/ap/${airport}?departureDate=${dep}&returnDate=${ret}&pa=2&py=0&pc=0&pi=0&sc=economy&flexDatesOffset=2`)}
function gyg(city:string){return partners.getyourguide.buildUrl(`https://www.getyourguide.pl/s/?q=${encodeURIComponent(city+' Christmas market')}`)}
export default function Page(){return <main><SiteHeader/><section className="seasonal-hero shell"><div className="kicker">SEZON TERAZ · JARMARKI 2026</div><h1>Jarmarki bożonarodzeniowe — wybierz weekend i leć po klimat.</h1><p>Nie chowamy ich w inspiracjach. Masz konkretne miasta, terminy, kalendarz jarmarków i od razu loty oraz bilety na atrakcje.</p></section>
<section className="section shell"><div className="seasonal-calendar">{ideas.map(i=><div key={i.city}><strong>{i.flag} {i.city}</strong><span>{i.market}</span></div>)}</div><div className="seasonal-grid">{ideas.map(i=><article className="seasonal-card" key={i.city}><img src={i.image} alt={`${i.city} — jarmarki bożonarodzeniowe`} /><div className="seasonal-card-body"><div className="kicker">PROPOZYCJA WYJAZDU</div><h2>{i.city}</h2><div className="seasonal-meta"><span>📅 {i.dates}</span><span>✈️ Warszawa</span><span>🛏️ 3 noce</span></div><p><b>Co zobaczyć:</b> {i.see}</p><div className="seasonal-actions"><a href={esky(i.city,i.airport,i.dates)} target="_blank" rel="sponsored noopener noreferrer">✈️ Sprawdź loty</a><a href={gyg(i.city)} target="_blank" rel="sponsored noopener noreferrer">🎟️ Atrakcje i bilety</a></div></div></article>)}</div></section><SiteFooter/></main>}
