export type DestinationImageRule = {
  label: string;
  query: string;
  localPath?: string;
};

/**
 * Źródło reguł: paczka użytkownika TRIPOWNIA_ZDJECIA_CALY_SWIAT,
 * plik kierunki.csv. Jedna warstwa mapowania dla całego portalu.
 */
const rules: Record<string, DestinationImageRule> = {
  "abu dhabi": { label: "Abu Dhabi", query: "Sheikh Zayed Grand Mosque Abu Dhabi UAE" },
  "agadir": { label: "Agadir", query: "Agadir beach Morocco" },
  "agra": { label: "Agra", query: "Taj Mahal Agra India" },
  "alanya": { label: "Alanya", query: "Alanya castle beach Turkey" },
  "algarve": { label: "Algarve", query: "Ponta da Piedade Algarve Portugal" },
  "alicante": { label: "Alicante", query: "Santa Barbara Castle Alicante Spain", localPath: "/images/destinations/alicante.jpg" },
  "amalfi": { label: "Amalfi", query: "Amalfi Coast Italy" },
  "amman": { label: "Amman", query: "Amman Citadel Jordan" },
  "amsterdam": { label: "Amsterdam", query: "Amsterdam canals Netherlands" , localPath: "/images/destinations/amsterdam.jpg" },
  "antalya": { label: "Antalya", query: "Antalya old town cliffs Turkey" },
  "antigua guatemala": { label: "Antigua Guatemala", query: "Antigua Guatemala volcano" },
  "antwerpia": { label: "Antwerpia", query: "Grote Markt Antwerp Belgium" },
  "arenal": { label: "Arenal", query: "Arenal Volcano Costa Rica" },
  "aruba": { label: "Aruba", query: "Eagle Beach Aruba divi divi" },
  "atacama": { label: "Atacama", query: "Atacama Desert Chile" },
  "ateny": { label: "Ateny", query: "Acropolis Athens Greece" , localPath: "/images/destinations/ateny.jpg" },
  "atitlan": { label: "Atitlan", query: "Lake Atitlan Guatemala" },
  "auckland": { label: "Auckland", query: "Sky Tower Auckland New Zealand" },
  "ayia napa": { label: "Ayia Napa", query: "Nissi Beach Ayia Napa Cyprus" },
  "azory": { label: "Azory", query: "Sete Cidades Azores Portugal" },
  "bahamy": { label: "Bahamy", query: "Bahamas aerial islands" },
  "balaton": { label: "Balaton", query: "Lake Balaton Hungary" },
  "bali": { label: "Bali", query: "Bali temple rice terraces Indonesia" },
  "banff": { label: "Banff", query: "Lake Louise Banff Canada" },
  "bangkok": { label: "Bangkok", query: "Wat Arun Bangkok Thailand" },
  "barbados": { label: "Barbados", query: "Barbados beach palms" },
  "barcelona": { label: "Barcelona", query: "Sagrada Familia Barcelona Spain", localPath: "/images/destinations/barcelona.jpg" },
  "bari": { label: "Bari", query: "Bari old town Adriatic Italy" },
  "bayahibe": { label: "Bayahibe", query: "Bayahibe Dominican Republic beach" },
  "belek": { label: "Belek", query: "Belek Turkey coast" },
  "belize": { label: "Belize", query: "Great Blue Hole Belize" },
  "benidorm": { label: "Benidorm", query: "Benidorm skyline beach Spain" },
  "bergen": { label: "Bergen", query: "Bryggen Bergen Norway" },
  "berlin": { label: "Berlin", query: "Brandenburg Gate Berlin Germany" , localPath: "/images/destinations/berlin.jpg" },
  "bled": { label: "Bled", query: "Lake Bled Slovenia" },
  "blue lagoon": { label: "Blue Lagoon", query: "Blue Lagoon Iceland" },
  "boa vista": { label: "Boa Vista", query: "Boa Vista Cape Verde dunes" },
  "bodrum": { label: "Bodrum", query: "Bodrum marina Turkey" },
  "bogota": { label: "Bogota", query: "Bogota Colombia panorama" },
  "bolonia": { label: "Bolonia", query: "Bologna Piazza Maggiore Italy" },
  "bora bora": { label: "Bora Bora", query: "Bora Bora Mount Otemanu lagoon" },
  "bordeaux": { label: "Bordeaux", query: "Place de la Bourse Bordeaux France" },
  "boston": { label: "Boston", query: "Boston waterfront USA" },
  "brisbane": { label: "Brisbane", query: "Brisbane skyline Australia" },
  "brno": { label: "Brno", query: "Brno Czech Republic old town" },
  "brugia": { label: "Brugia", query: "Bruges canals Belgium" },
  "bruksela": { label: "Bruksela", query: "Grand Place Brussels Belgium" },
  "budapeszt": { label: "Budapeszt", query: "Hungarian Parliament Budapest Danube", localPath: "/images/destinations/budapeszt.jpg" },
  "budva": { label: "Budva", query: "Budva old town Montenegro" },
  "buenos aires": { label: "Buenos Aires", query: "Obelisk Buenos Aires Argentina" },
  "bukareszt": { label: "Bukareszt", query: "Palace of Parliament Bucharest Romania" },
  "busan": { label: "Busan", query: "Haeundae Beach Busan South Korea" },
  "cancun": { label: "Cancun", query: "Cancun Mexico beach" },
  "capri": { label: "Capri", query: "Faraglioni Capri Italy" },
  "cartagena": { label: "Cartagena", query: "Cartagena Colombia colorful streets" },
  "casablanca": { label: "Casablanca", query: "Hassan II Mosque Casablanca Morocco" },
  "chalkidiki": { label: "Chalkidiki", query: "Halkidiki Greece coast" },
  "chefchaouen": { label: "Chefchaouen", query: "Chefchaouen blue streets Morocco" },
  "chiang mai": { label: "Chiang Mai", query: "Chiang Mai Thailand temple mountains" },
  "chicago": { label: "Chicago", query: "Chicago skyline USA" },
  "cinque terre": { label: "Cinque Terre", query: "Manarola Cinque Terre Italy" },
  "cliffs of moher": { label: "Cliffs of Moher", query: "Cliffs of Moher Ireland" },
  "colombo": { label: "Colombo", query: "Colombo Sri Lanka skyline" },
  "comino": { label: "Comino", query: "Blue Lagoon Comino Malta" },
  "costa blanca": { label: "Costa Blanca", query: "Costa Blanca Spain coast" },
  "costa brava": { label: "Costa Brava", query: "Costa Brava coastline Spain" },
  "costa del sol": { label: "Costa del Sol", query: "Costa del Sol Spain coast" },
  "cote d azur": { label: "Cote d Azur", query: "French Riviera Cote d Azur" },
  "cusco": { label: "Cusco", query: "Plaza de Armas Cusco Peru" },
  "da nang": { label: "Da Nang", query: "Dragon Bridge Da Nang Vietnam" },
  "delhi": { label: "Delhi", query: "India Gate Delhi India" },
  "diani beach": { label: "Diani Beach", query: "Diani Beach Kenya" },
  "djerba": { label: "Djerba", query: "Djerba Tunisia beach" },
  "doha": { label: "Doha", query: "Doha skyline Qatar" },
  "drezno": { label: "Drezno", query: "Dresden old town Germany" },
  "dubaj": { label: "Dubaj", query: "Burj Khalifa Dubai UAE", localPath: "/images/destinations/dubaj.jpg" },
  "dublin": { label: "Dublin", query: "Ha penny Bridge Dublin Ireland", localPath: "/images/destinations/dublin.jpg" },
  "dubrownik": { label: "Dubrownik", query: "Dubrovnik old town Croatia aerial" , localPath: "/images/destinations/dubrownik.jpg" },
  "edynburg": { label: "Edynburg", query: "Edinburgh Castle Scotland", localPath: "/images/destinations/edynburg.jpg" },
  "eilat": { label: "Eilat", query: "Eilat Red Sea Israel" },
  "ella": { label: "Ella", query: "Nine Arch Bridge Ella Sri Lanka" },
  "everest": { label: "Everest", query: "Mount Everest Himalaya" },
  "faro": { label: "Faro", query: "Faro Algarve Portugal" },
  "fez": { label: "Fez", query: "Fez medina Morocco" },
  "fiji": { label: "Fiji", query: "Fiji island lagoon" },
  "florencja": { label: "Florencja", query: "Florence Duomo panorama Italy" , localPath: "/images/destinations/florencja.jpg" },
  "frankfurt": { label: "Frankfurt", query: "Frankfurt skyline Germany" },
  "fuerteventura": { label: "Fuerteventura", query: "Fuerteventura beach dunes Spain", localPath: "/images/destinations/fuerteventura.jpg" },
  "fuji": { label: "Fuji", query: "Mount Fuji Japan lake" },
  "funchal": { label: "Funchal", query: "Funchal Madeira Portugal panorama" },
  "galapagos": { label: "Galapagos", query: "Galapagos Ecuador coast wildlife" },
  "galle": { label: "Galle", query: "Galle Fort Sri Lanka" },
  "galway": { label: "Galway", query: "Galway Ireland colourful streets" },
  "garden route": { label: "Garden Route", query: "Garden Route South Africa coast" },
  "gdansk": { label: "Gdansk", query: "Gdansk Long Market Poland" },
  "geirangerfjord": { label: "Geirangerfjord", query: "Geirangerfjord Norway" },
  "genewa": { label: "Genewa", query: "Jet d Eau Geneva Switzerland" },
  "girona": { label: "Girona", query: "Girona old town Spain" },
  "goa": { label: "Goa", query: "Goa India beach" },
  "gold coast": { label: "Gold Coast", query: "Gold Coast Australia beach skyline" },
  "goteborg": { label: "Goteborg", query: "Gothenburg waterfront Sweden" },
  "gozo": { label: "Gozo", query: "Gozo Citadel Malta" },
  "gran canaria": { label: "Gran Canaria", query: "Maspalomas dunes Gran Canaria Spain" },
  "granada": { label: "Granada", query: "Alhambra Granada Spain" },
  "grand canyon": { label: "Grand Canyon", query: "Grand Canyon USA" },
  "great barrier reef": { label: "Great Barrier Reef", query: "Great Barrier Reef Australia aerial" },
  "guilin": { label: "Guilin", query: "Guilin karst mountains China" },
  "ha long": { label: "Ha Long", query: "Ha Long Bay Vietnam" },
  "haga": { label: "Haga", query: "Binnenhof The Hague Netherlands" },
  "hamburg": { label: "Hamburg", query: "Speicherstadt Hamburg Germany" },
  "hammamet": { label: "Hammamet", query: "Hammamet medina Tunisia" },
  "hanoi": { label: "Hanoi", query: "Hoan Kiem Hanoi Vietnam" },
  "hawaje": { label: "Hawaje", query: "Waikiki Diamond Head Hawaii" },
  "hawana": { label: "Hawana", query: "Havana Cuba old cars" },
  "helsinki": { label: "Helsinki", query: "Helsinki Cathedral Finland", localPath: "/images/destinations/helsinki.jpg" },
  "hiroshima": { label: "Hiroshima", query: "Itsukushima Torii Hiroshima Japan" },
  "ho chi minh": { label: "Ho Chi Minh", query: "Ho Chi Minh City skyline Vietnam" },
  "hoi an": { label: "Hoi An", query: "Hoi An lanterns Vietnam" },
  "hongkong": { label: "Hongkong", query: "Victoria Harbour Hong Kong" },
  "hurghada": { label: "Hurghada", query: "Hurghada marina Red Sea Egypt" },
  "hvar": { label: "Hvar", query: "Hvar Croatia harbour" },
  "ibiza": { label: "Ibiza", query: "Dalt Vila Ibiza Spain" },
  "iguazu": { label: "Iguazu", query: "Iguazu Falls Brazil Argentina" },
  "innsbruck": { label: "Innsbruck", query: "Innsbruck Alps Austria" },
  "interlaken": { label: "Interlaken", query: "Interlaken Alps Switzerland" },
  "islandia": { label: "Islandia", query: "Iceland waterfall landscape" },
  "izmir": { label: "Izmir", query: "Izmir waterfront Turkey" },
  "jaipur": { label: "Jaipur", query: "Hawa Mahal Jaipur India" },
  "jakarta": { label: "Jakarta", query: "Jakarta skyline Indonesia" },
  "jeju": { label: "Jeju", query: "Jeju island South Korea" },
  "jerozolima": { label: "Jerozolima", query: "Jerusalem Old City" },
  "johannesburg": { label: "Johannesburg", query: "Johannesburg skyline South Africa" },
  "kair": { label: "Kair", query: "Giza pyramids Cairo Egypt" , localPath: "/images/destinations/kair.jpg" },
  "kapadocja": { label: "Kapadocja", query: "Cappadocia balloons Goreme Turkey" },
  "kapsztad": { label: "Kapsztad", query: "Table Mountain Cape Town South Africa" },
  "karlowe wary": { label: "Karlowe Wary", query: "Karlovy Vary Czech Republic" },
  "katania": { label: "Katania", query: "Catania Etna Sicily Italy" },
  "kathmandu": { label: "Kathmandu", query: "Kathmandu Nepal temples Himalaya" },
  "kerala": { label: "Kerala", query: "Kerala backwaters India" },
  "kilimandzaro": { label: "Kilimandzaro", query: "Mount Kilimanjaro Tanzania" },
  "kioto": { label: "Kioto", query: "Fushimi Inari Kyoto Japan" },
  "koh samui": { label: "Koh Samui", query: "Koh Samui Thailand beach" },
  "kolonia": { label: "Kolonia", query: "Cologne Cathedral Germany" },
  "komodo": { label: "Komodo", query: "Komodo islands Indonesia" },
  "kopenhaga": { label: "Kopenhaga", query: "Nyhavn Copenhagen Denmark", localPath: "/images/destinations/kopenhaga.jpg" },
  "kordoba": { label: "Kordoba", query: "Mezquita Cordoba Spain" },
  "korfu": { label: "Korfu", query: "Paleokastritsa Corfu Greece" },
  "korsyka": { label: "Korsyka", query: "Bonifacio Corsica France" },
  "kos": { label: "Kos", query: "Kos Greece coast" },
  "kotor": { label: "Kotor", query: "Bay of Kotor Montenegro" },
  "krabi": { label: "Krabi", query: "Railay Beach Krabi Thailand" },
  "krakow": { label: "Krakow", query: "Krakow Main Square Poland" },
  "kreta": { label: "Kreta", query: "Balos Lagoon Crete Greece" },
  "kruger": { label: "Kruger", query: "Kruger National Park South Africa" },
  "ksamil": { label: "Ksamil", query: "Ksamil Albania islands" },
  "kuala lumpur": { label: "Kuala Lumpur", query: "Petronas Towers Kuala Lumpur Malaysia" },
  "kyrenia": { label: "Kyrenia", query: "Kyrenia Harbour Cyprus" },
  "la digue": { label: "La Digue", query: "Anse Source d Argent La Digue Seychelles" },
  "la paz": { label: "La Paz", query: "La Paz Bolivia Andes" },
  "langkawi": { label: "Langkawi", query: "Langkawi Sky Bridge Malaysia" },
  "lanzarote": { label: "Lanzarote", query: "Timanfaya Lanzarote Spain" },
  "laponia": { label: "Laponia", query: "Lapland Finland aurora winter" },
  "larnaka": { label: "Larnaka", query: "Larnaca promenade Cyprus" },
  "las vegas": { label: "Las Vegas", query: "Las Vegas Strip USA" },
  "lima": { label: "Lima", query: "Miraflores Lima Peru Pacific" },
  "limassol": { label: "Limassol", query: "Limassol marina Cyprus" },
  "liverpool": { label: "Liverpool", query: "Liverpool waterfront UK" },
  "lizbona": { label: "Lizbona", query: "Lisbon yellow tram Portugal", localPath: "/images/destinations/lizbona.jpg" },
  "lofoty": { label: "Lofoty", query: "Lofoten Norway red cabins mountains" },
  "londyn": { label: "Londyn", query: "Big Ben Westminster London UK", localPath: "/images/destinations/londyn.jpg" },
  "los angeles": { label: "Los Angeles", query: "Hollywood Sign Los Angeles USA" },
  "los cabos": { label: "Los Cabos", query: "El Arco Los Cabos Mexico" },
  "lublana": { label: "Lublana", query: "Ljubljana Slovenia old town" },
  "lucerna": { label: "Lucerna", query: "Chapel Bridge Lucerne Switzerland" },
  "luxor": { label: "Luxor", query: "Karnak Luxor Egypt" },
  "lyon": { label: "Lyon", query: "Lyon old town France panorama" },
  "machu picchu": { label: "Machu Picchu", query: "Machu Picchu Peru" },
  "madeira": { label: "Madeira", query: "Madeira cliffs mountains Portugal" },
  "madera": { label: "Madeira", query: "Madeira cliffs mountains Portugal" },
  "madryt": { label: "Madryt", query: "Plaza Mayor Madrid Spain", localPath: "/images/destinations/madryt.jpg" },
  "mahe": { label: "Mahe", query: "Mahe Seychelles beach" },
  "majorka": { label: "Majorka", query: "Palma Cathedral Mallorca Spain", localPath: "/images/destinations/majorka.jpg" },
  "makarska": { label: "Makarska", query: "Makarska Biokovo Croatia" },
  "malaga": { label: "Malaga", query: "Malaga port Alcazaba Spain", localPath: "/images/destinations/malaga.jpg" },
  "male": { label: "Male", query: "Male Maldives" },
  "malediwy": { label: "Malediwy", query: "Maldives aerial lagoon" },
  "malta": { label: "Valletta", query: "Valletta Grand Harbour Malta", localPath: "/images/destinations/valletta.jpg" },
  "manchester": { label: "Manchester", query: "Manchester city centre UK" },
  "manuel antonio": { label: "Manuel Antonio", query: "Manuel Antonio Costa Rica beach" },
  "marmaris": { label: "Marmaris", query: "Marmaris bay Turkey" },
  "marrakesz": { label: "Marrakesz", query: "Jemaa el Fnaa Marrakech Morocco" , localPath: "/images/destinations/marrakesz.jpg" },
  "marsa alam": { label: "Marsa Alam", query: "Marsa Alam Red Sea Egypt" },
  "marsylia": { label: "Marsylia", query: "Vieux Port Marseille France" },
  "masai mara": { label: "Masai Mara", query: "Masai Mara Kenya safari" },
  "maskat": { label: "Maskat", query: "Sultan Qaboos Mosque Muscat Oman" },
  "mauritius": { label: "Mauritius", query: "Le Morne Mauritius lagoon" },
  "mazury": { label: "Mazury", query: "Masurian lakes Poland" },
  "medellin": { label: "Medellin", query: "Medellin Colombia valley" },
  "mediolan": { label: "Mediolan", query: "Duomo Milan Italy" , localPath: "/images/destinations/mediolan.jpg" },
  "melbourne": { label: "Melbourne", query: "Melbourne skyline Australia" },
  "mellieha": { label: "Mellieha", query: "Mellieha Bay Malta" },
  "mexico city": { label: "Mexico City", query: "Palacio de Bellas Artes Mexico City" },
  "miami": { label: "Miami", query: "South Beach Miami USA" },
  "milford sound": { label: "Milford Sound", query: "Milford Sound New Zealand" },
  "minorka": { label: "Minorka", query: "Cala Macarella Menorca Spain" },
  "mombasa": { label: "Mombasa", query: "Mombasa Kenya beach" },
  "monachium": { label: "Monachium", query: "Marienplatz Munich Germany", localPath: "/images/destinations/monachium.jpg" },
  "montego bay": { label: "Montego Bay", query: "Montego Bay Jamaica" },
  "montreal": { label: "Montreal", query: "Old Montreal Canada" },
  "morze martwe": { label: "Morze Martwe", query: "Dead Sea Jordan" },
  "mumbai": { label: "Mumbai", query: "Gateway of India Mumbai" },
  "mykonos": { label: "Mykonos", query: "Mykonos windmills Greece" },
  "nairobi": { label: "Nairobi", query: "Nairobi Kenya skyline" },
  "nassau": { label: "Nassau", query: "Nassau Bahamas lagoon" },
  "neapol": { label: "Neapol", query: "Naples Vesuvius Italy panorama", localPath: "/images/destinations/neapol.jpg" },
  "negril": { label: "Negril", query: "Seven Mile Beach Negril Jamaica" },
  "nessebar": { label: "Nessebar", query: "Nessebar old town Bulgaria" },
  "niagara": { label: "Niagara", query: "Niagara Falls Canada" },
  "nicea": { label: "Nicea", query: "Promenade des Anglais Nice France", localPath: "/images/destinations/nicea.jpg" },
  "ninh binh": { label: "Ninh Binh", query: "Ninh Binh Vietnam river mountains" },
  "nowy jork": { label: "Nowy Jork", query: "Manhattan Brooklyn Bridge New York USA" },
  "nowy orlean": { label: "Nowy Orlean", query: "French Quarter New Orleans USA" },
  "nusa penida": { label: "Nusa Penida", query: "Kelingking Beach Nusa Penida" },
  "ocho rios": { label: "Ocho Rios", query: "Dunns River Falls Jamaica" },
  "orlando": { label: "Orlando", query: "Orlando Florida USA" },
  "osaka": { label: "Osaka", query: "Dotonbori Osaka Japan" },
  "oslo": { label: "Oslo", query: "Oslo Opera House Norway" },
  "oxford": { label: "Oxford", query: "Oxford university architecture UK" },
  "pafos": { label: "Pafos", query: "Aphrodite Rock Paphos Cyprus" },
  "palermo": { label: "Palermo", query: "Palermo Cathedral Sicily Italy" },
  "panama canal": { label: "Panama Canal", query: "Panama Canal" },
  "panama city": { label: "Panama City", query: "Panama City skyline Panama" },
  "paryz": { label: "Paryz", query: "Eiffel Tower Paris France", localPath: "/images/destinations/paryz.jpg" },
  "patagonia": { label: "Patagonia", query: "Patagonia Fitz Roy Argentina" },
  "pekin": { label: "Pekin", query: "Great Wall Beijing China" },
  "penang": { label: "Penang", query: "George Town Penang Malaysia" },
  "perth": { label: "Perth", query: "Perth Swan River Australia" },
  "petra": { label: "Petra", query: "Petra Treasury Jordan" },
  "phi phi": { label: "Phi Phi", query: "Maya Bay Phi Phi Thailand" },
  "phu quoc": { label: "Phu Quoc", query: "Phu Quoc Vietnam beach" },
  "phuket": { label: "Phuket", query: "Phuket Thailand coast" },
  "piza": { label: "Piza", query: "Leaning Tower Pisa Italy" },
  "playa del carmen": { label: "Playa del Carmen", query: "Playa del Carmen Mexico beach" },
  "pokhara": { label: "Pokhara", query: "Pokhara Nepal Annapurna lake" },
  "porto": { label: "Porto", query: "Ribeira Dom Luis I Porto Portugal", localPath: "/images/destinations/porto.jpg" },
  "positano": { label: "Positano", query: "Positano Italy coast" },
  "poznan": { label: "Poznan", query: "Poznan Old Market Poland" },
  "praga": { label: "Praga", query: "Charles Bridge Prague Czech Republic", localPath: "/images/destinations/praga.jpg" },
  "praslin": { label: "Praslin", query: "Anse Lazio Praslin Seychelles" },
  "protaras": { label: "Protaras", query: "Fig Tree Bay Protaras Cyprus" },
  "pula": { label: "Pula", query: "Pula Arena Croatia" },
  "punta cana": { label: "Punta Cana", query: "Punta Cana Dominican Republic beach" },
  "quebec": { label: "Quebec", query: "Chateau Frontenac Quebec City Canada" },
  "queenstown": { label: "Queenstown", query: "Queenstown New Zealand lake mountains" },
  "quito": { label: "Quito", query: "Quito Ecuador old town Andes" },
  "ras al khaimah": { label: "Ras Al Khaimah", query: "Ras Al Khaimah UAE mountains coast" },
  "reykjavik": { label: "Reykjavik", query: "Hallgrimskirkja Reykjavik Iceland" },
  "rio de janeiro": { label: "Rio de Janeiro", query: "Christ the Redeemer Rio de Janeiro Brazil" },
  "riviera maya": { label: "Riviera Maya", query: "Riviera Maya Mexico beach cenote" },
  "riwiera albanska": { label: "Saranda", query: "Saranda Albania coast" },
  "rodos": { label: "Rodos", query: "Rhodes old town Greece" },
  "rotorua": { label: "Rotorua", query: "Rotorua geothermal New Zealand" },
  "rotterdam": { label: "Rotterdam", query: "Rotterdam skyline Netherlands" },
  "rovaniemi": { label: "Rovaniemi", query: "Rovaniemi Finland winter" },
  "rovinj": { label: "Rovinj", query: "Rovinj Croatia old town" },
  "rzym": { label: "Rzym", query: "Colosseum Rome Italy", localPath: "/images/destinations/rzym.jpg" },
  "sal": { label: "Sal", query: "Santa Maria Beach Sal Cape Verde" },
  "salalah": { label: "Salalah", query: "Salalah Oman coast palms" },
  "saloniki": { label: "Saloniki", query: "White Tower Thessaloniki Greece" },
  "salvador": { label: "Salvador", query: "Pelourinho Salvador Brazil" },
  "salzburg": { label: "Salzburg", query: "Salzburg old town fortress Austria" },
  "san francisco": { label: "San Francisco", query: "Golden Gate Bridge San Francisco USA" },
  "san jose cr": { label: "San Jose CR", query: "San Jose Costa Rica" },
  "san juan": { label: "San Juan", query: "Old San Juan Puerto Rico" },
  "santiago": { label: "Santiago", query: "Santiago Chile skyline Andes" },
  "santo domingo": { label: "Santo Domingo", query: "Zona Colonial Santo Domingo" },
  "santorini": { label: "Santorini", query: "Oia Santorini Greece blue domes" , localPath: "/images/destinations/santorini.jpg" },
  "sao paulo": { label: "Sao Paulo", query: "Sao Paulo skyline Brazil" },
  "saranda": { label: "Saranda", query: "Saranda Albania coast" },
  "sardynia": { label: "Sardynia", query: "Costa Smeralda Sardinia Italy" },
  "seattle": { label: "Seattle", query: "Space Needle Seattle USA" },
  "seminyak": { label: "Seminyak", query: "Seminyak Bali beach sunset" },
  "serengeti": { label: "Serengeti", query: "Serengeti Tanzania safari" },
  "seul": { label: "Seul", query: "N Seoul Tower Seoul South Korea" },
  "sewilla": { label: "Sewilla", query: "Plaza de Espana Seville Spain", localPath: "/images/destinations/sewilla.jpg" },
  "sharm el sheikh": { label: "Sharm el Sheikh", query: "Sharm el Sheikh Red Sea Egypt" },
  "side": { label: "Side", query: "Temple of Apollo Side Turkey" },
  "sigiriya": { label: "Sigiriya", query: "Sigiriya Sri Lanka" },
  "singapur": { label: "Singapur", query: "Marina Bay Sands Singapore" },
  "sliema": { label: "Sliema", query: "Sliema Valletta waterfront Malta" },
  "sloneczny brzeg": { label: "Sloneczny Brzeg", query: "Sunny Beach Bulgaria" },
  "sofia": { label: "Sofia", query: "Alexander Nevsky Cathedral Sofia Bulgaria" },
  "sopot": { label: "Sopot", query: "Sopot pier Poland" },
  "sousse": { label: "Sousse", query: "Sousse medina Tunisia" },
  "split": { label: "Split", query: "Diocletian Palace Split Croatia", localPath: "/images/destinations/split.jpg" },
  "st julian's": { label: "St Julians", query: "Spinola Bay St Julians Malta" },
  "st julians": { label: "St Julians", query: "Spinola Bay St Julians Malta" },
  "stambul": { label: "Stambul", query: "Hagia Sophia Istanbul Turkey", localPath: "/images/destinations/stambul.jpg" },
  "stone town": { label: "Stone Town", query: "Stone Town Zanzibar" },
  "strasburg": { label: "Strasburg", query: "Petite France Strasbourg" },
  "sycylia": { label: "Sycylia", query: "Mount Etna Sicily Italy" },
  "sydney": { label: "Sydney", query: "Sydney Opera House Australia" },
  "szanghaj": { label: "Szanghaj", query: "Shanghai Pudong skyline China" },
  "sztokholm": { label: "Sztokholm", query: "Gamla Stan Stockholm Sweden" },
  "tahiti": { label: "Tahiti", query: "Tahiti mountains ocean French Polynesia" },
  "taormina": { label: "Taormina", query: "Taormina Etna Sicily Italy" },
  "tel aviv": { label: "Tel Aviv", query: "Tel Aviv skyline beach Israel" },
  "teneryfa": { label: "Teneryfa", query: "Teide Tenerife Spain", localPath: "/images/destinations/teneryfa.jpg" },
  "tirana": { label: "Tirana", query: "Skanderbeg Square Tirana Albania" },
  "tokio": { label: "Tokio", query: "Tokyo Tower skyline Japan" },
  "toronto": { label: "Toronto", query: "CN Tower Toronto Canada" },
  "torres del paine": { label: "Torres del Paine", query: "Torres del Paine Chile" },
  "transylwania": { label: "Transylwania", query: "Bran Castle Transylvania Romania" },
  "tromso": { label: "Tromso", query: "Tromso Norway mountains" },
  "tulum": { label: "Tulum", query: "Tulum ruins Mexico" },
  "tuluza": { label: "Tuluza", query: "Toulouse France city" },
  "tunis": { label: "Tunis", query: "Sidi Bou Said Tunisia" },
  "turyn": { label: "Turyn", query: "Mole Antonelliana Turin Italy" },
  "ubud": { label: "Ubud", query: "Ubud rice terraces Bali" },
  "uluru": { label: "Uluru", query: "Uluru Australia" },
  "ushuaia": { label: "Ushuaia", query: "Ushuaia Beagle Channel Argentina" },
  "uyuni": { label: "Uyuni", query: "Salar de Uyuni Bolivia" },
  "valletta": { label: "Valletta", query: "Valletta Grand Harbour Malta", localPath: "/images/destinations/valletta.jpg" },
  "vancouver": { label: "Vancouver", query: "Vancouver skyline mountains Canada" },
  "varadero": { label: "Varadero", query: "Varadero Cuba beach" },
  "wadi rum": { label: "Wadi Rum", query: "Wadi Rum Jordan desert" },
  "wadi shab": { label: "Wadi Shab", query: "Wadi Shab Oman" },
  "walencja": { label: "Walencja", query: "City of Arts and Sciences Valencia Spain", localPath: "/images/destinations/walencja.jpg" },
  "warszawa": { label: "Warszawa", query: "Warsaw skyline Palace of Culture Poland" },
  "washington dc": { label: "Washington DC", query: "US Capitol Washington DC" },
  "wellington": { label: "Wellington", query: "Wellington waterfront New Zealand" },
  "wenecja": { label: "Wenecja", query: "Grand Canal Venice gondolas Italy" , localPath: "/images/destinations/wenecja.jpg" },
  "werona": { label: "Werona", query: "Verona Arena Italy" },
  "wieden": { label: "Wieden", query: "Schonbrunn Vienna Austria", localPath: "/images/destinations/wieden.jpg" },
  "wroclaw": { label: "Wroclaw", query: "Wroclaw Market Square Poland" },
  "xian": { label: "Xian", query: "Terracotta Army Xian China" },
  "yellowstone": { label: "Yellowstone", query: "Grand Prismatic Spring Yellowstone USA" },
  "yosemite": { label: "Yosemite", query: "Half Dome Yosemite USA" },
  "zadar": { label: "Zadar", query: "Zadar old town Croatia", localPath: "/images/destinations/zadar.jpg" },
  "zakopane": { label: "Zakopane", query: "Zakopane Tatra Mountains Poland" },
  "zakynthos": { label: "Zakynthos", query: "Navagio Zakynthos Greece" },
  "zanzibar": { label: "Zanzibar", query: "Zanzibar beach Tanzania" },
  "zermatt": { label: "Zermatt", query: "Matterhorn Zermatt Switzerland" },
  "zlote piaski": { label: "Zlote Piaski", query: "Golden Sands Bulgaria" },
  "zurych": { label: "Zurych", query: "Zurich lake old town Switzerland", localPath: "/images/destinations/zurych.jpg" },
};

function normalize(value: string) {
  return value
    .trim()
    .toLocaleLowerCase("pl")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ");
}

export function getDestinationImageRule(city: string, country: string): DestinationImageRule {
  const key = normalize(city);
  if (rules[key]) return rules[key];

  // Bez zgadywania konkretnego landmarku, jeśli kierunku nie ma w paczce.
  // Używamy neutralnego zapytania dokładnie dla miasta/kraju.
  return {
    label: city,
    query: `${city} ${country} iconic view travel landscape`,
  };
}

export const destinationImageRuleCount = 345;
