import type { PartnerKey } from "./partners";
import { partners } from "./partners";

export type Offer = {
  id: number; flag: string; city: string; country: string; price: number; departure: string; airportCode: string;
  nights: number; weather: string; score: number; tag: "BIERZEMY" | "DOBRA OPCJA" | "OKAZJA"; reason: string;
  image: string; category: string[]; hotel: string; board: string; dates: string; partner: PartnerKey; affiliateUrl: string;
};

export const offers: Offer[] = [
  { id:1, flag:"🇲🇹", city:"Malta", country:"Malta", price:699, departure:"Warszawa Modlin", airportCode:"WMI", nights:3, weather:"20°C", score:9.6, tag:"BIERZEMY", reason:"Bardzo dobra cena, sensowny termin i świetny kierunek na szybki city break.", image:"https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1600&q=80", category:["city","tanio","cieplo","weekend"], hotel:"St. Julian's Bay", board:"Bez wyżywienia", dates:"23–26 listopada 2026", partner:"esky", affiliateUrl:partners.esky.buildUrl("https://www2.esky.pl/lot+hotel/portfolio?rooms%5B0%5D%5Badults%5D=2&datesTab=flexDates&stayLength=2:4&arrivalPlaces=co-MT&context=pl-packages") },
  { id:2, flag:"🇪🇸", city:"Barcelona", country:"Hiszpania", price:1099, departure:"Warszawa", airportCode:"WAW", nights:3, weather:"22°C", score:9.2, tag:"DOBRA OPCJA", reason:"Dobry balans ceny, lotu i lokalizacji. Idealny krótki wypad.", image:"https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1600&q=80", category:["city","weekend","cieplo"], hotel:"Hotel w centrum", board:"Śniadanie", dates:"wybrane terminy jesień 2026", partner:"esky", affiliateUrl:partners.esky.buildUrl("https://www2.esky.pl/lot+hotel/portfolio?rooms%5B0%5D%5Badults%5D=2&datesTab=flexDates&stayLength=2:4&arrivalPlaces=ci-BCN&context=pl-packages") },
  { id:3, flag:"🇹🇳", city:"Djerba", country:"Tunezja", price:1799, departure:"Warszawa", airportCode:"WAW", nights:7, weather:"26°C", score:9.4, tag:"BIERZEMY", reason:"7 nocy All Inclusive i ciepło — bardzo mocna relacja ceny do długości wyjazdu.", image:"https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1600&q=80", category:["plaza","cieplo","allinclusive"], hotel:"Resort 4★", board:"All Inclusive", dates:"wybrane terminy jesień 2026", partner:"exim", affiliateUrl:partners.exim.buildUrl() },
  { id:4, flag:"🇮🇹", city:"Bergamo", country:"Włochy", price:599, departure:"Kraków", airportCode:"KRK", nights:2, weather:"18°C", score:8.8, tag:"OKAZJA", reason:"Bardzo tani szybki wypad i świetna baza do Mediolanu lub nad Como.", image:"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1600&q=80", category:["city","tanio","weekend"], hotel:"Hotel 3★", board:"Bez wyżywienia", dates:"wybrane weekendy 2026", partner:"esky", affiliateUrl:partners.esky.buildUrl("https://www2.esky.pl/lot+hotel/portfolio?rooms%5B0%5D%5Badults%5D=2&datesTab=flexDates&stayLength=2:3&arrivalPlaces=co-IT&context=pl-packages") },
  { id:5, flag:"🇪🇬", city:"Hurghada", country:"Egipt", price:2199, departure:"Katowice", airportCode:"KTW", nights:7, weather:"29°C", score:9.1, tag:"DOBRA OPCJA", reason:"Ciepło poza sezonem, 7 nocy i wygodny pakiet z wyżywieniem.", image:"https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1600&q=80", category:["plaza","cieplo","allinclusive"], hotel:"Resort 4★", board:"All Inclusive", dates:"wybrane terminy 2026", partner:"tui", affiliateUrl:partners.tui.buildUrl() },
  { id:6, flag:"🇬🇷", city:"Kreta", country:"Grecja", price:2399, departure:"Warszawa", airportCode:"WAW", nights:7, weather:"25°C", score:9.0, tag:"DOBRA OPCJA", reason:"Klasyczny tygodniowy wypoczynek z dobrym balansem ceny i jakości.", image:"https://images.unsplash.com/photo-1504512485720-7d83a16ee930?auto=format&fit=crop&w=1600&q=80", category:["plaza","cieplo","allinclusive"], hotel:"Hotel 4★", board:"All Inclusive", dates:"wybrane terminy 2026", partner:"wakacje", affiliateUrl:partners.wakacje.buildUrl() }
];
