import type { Metadata } from "next";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { partners } from "@/lib/partners";
export const metadata:Metadata={title:"Sylwester 2026/2027 — pomysły i konkretne wyjazdy | Tripownia.pl",description:"Sylwester w Rzymie, Budapeszcie, Lizbonie i Dubaju: konkretne terminy, loty, noclegi i atrakcje.",alternates:{canonical:"/sylwester"}};
const ideas=[
 {city:"Rzym",flag:"🇮🇹",airport:"ROM",dates:["2026-12-29","2027-01-02"],image:"/images/destinations/rzym.jpg",why:"Plac, kolacja, nocny spacer i 3 pełne dni na zwiedzanie.",see:"Koloseum · Forum Romanum · Watykan · Trastevere · punkty widokowe"},
 {city:"Budapeszt",flag:"🇭🇺",airport:"BUD",dates:["2026-12-30","2027-01-03"],image:"/images/destinations/budapeszt.jpg",why:"Termy w dzień, Dunaj nocą i świetny city break bez długiego lotu.",see:"Parlament · Baszta Rybacka · termy Széchenyi · rejs po Dunaju · Bazylika"},
 {city:"Lizbona",flag:"🇵🇹",airport:"LIS",dates:["2026-12-29","2027-01-03"],image:"/images/destinations/lizbona.jpg",why:"Łagodniejsza pogoda, punkty widokowe i ocean na początek roku.",see:"Alfama · Belém · Praça do Comércio · Miradouros · Sintra"},
 {city:"Dubaj",flag:"🇦🇪",airport:"DXB",dates:["2026-12-28","2027-01-03"],image:"/images/destinations/dubaj.jpg",why:"Ciepło, spektakularna noc sylwestrowa i kilka dni plaży.",see:"Burj Khalifa · Marina · pustynia · Dubai Creek · plaża"},
];
function flightSearch(i:any){const u=new URL("https://www.kiwi.com/deep");u.searchParams.set("from","WAW");u.searchParams.set("to",i.airport);u.searchParams.set("departure",i.dates[0]);u.searchParams.set("return",i.dates[1]);u.searchParams.set("currency","PLN");return partners.kiwi.buildUrl(u.toString())}
function gyg(city:string){return partners.getyourguide.buildUrl(`https://www.getyourguide.pl/s/?q=${encodeURIComponent(city+' New Year')}`)}
export default function Page(){return <main><SiteHeader/><section className="seasonal-hero shell"><div className="kicker">SYLWESTER 2026/2027</div><h1>Nie pytamy „gdzie na Sylwestra?”. Dajemy gotowe warianty.</h1><p>Terminy są ustawione wokół 31 grudnia, a w wyszukiwarce lotów możesz od razu przesunąć daty i sprawdzić tańszy wariant.</p></section><section className="section shell"><div className="seasonal-grid">{ideas.map(i=><article className="seasonal-card" key={i.city}><img src={i.image} alt={`${i.city} na Sylwestra`} /><div className="seasonal-card-body"><div className="kicker">{i.flag} SYLWESTER</div><h2>{i.city}</h2><div className="seasonal-meta"><span>📅 {i.dates[0]} → {i.dates[1]}</span><span>✈️ Warszawa</span></div><p>{i.why}</p><p><b>Co zobaczyć:</b> {i.see}</p><div className="seasonal-actions"><a href={flightSearch(i)} target="_blank" rel="sponsored noopener noreferrer">✈️ Sprawdź loty</a><a href={gyg(i.city)} target="_blank" rel="sponsored noopener noreferrer">🎟️ Co robić / bilety</a></div></div></article>)}</div></section><SiteFooter/></main>}
